# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `nokogiri-html5-inference` gem.
# Please instead update this file by running `bin/tapioca gem nokogiri-html5-inference`.


# source://nokogiri-html5-inference//lib/nokogiri/html5/inference/version.rb#3
module Nokogiri
  class << self
    # source://nokogiri/1.15.2/lib/nokogiri/html4.rb#10
    def HTML(input, url = T.unsafe(nil), encoding = T.unsafe(nil), options = T.unsafe(nil), &block); end

    # source://nokogiri/1.15.2/lib/nokogiri/html4.rb#10
    def HTML4(input, url = T.unsafe(nil), encoding = T.unsafe(nil), options = T.unsafe(nil), &block); end

    # source://nokogiri/1.15.2/lib/nokogiri/html5.rb#30
    def HTML5(input, url = T.unsafe(nil), encoding = T.unsafe(nil), **options, &block); end

    # source://nokogiri/1.15.2/lib/nokogiri.rb#91
    def Slop(*args, &block); end

    # source://nokogiri/1.15.2/lib/nokogiri/xml.rb#7
    def XML(thing, url = T.unsafe(nil), encoding = T.unsafe(nil), options = T.unsafe(nil), &block); end

    # source://nokogiri/1.15.2/lib/nokogiri/xslt.rb#13
    def XSLT(stylesheet, modules = T.unsafe(nil)); end

    # source://nokogiri/1.15.2/lib/nokogiri.rb#96
    def install_default_aliases; end

    # source://nokogiri/1.15.2/lib/nokogiri/version/info.rb#205
    def jruby?; end

    # source://nokogiri/1.15.2/lib/nokogiri/version/info.rb#210
    def libxml2_patches; end

    # source://nokogiri/1.15.2/lib/nokogiri.rb#68
    def make(input = T.unsafe(nil), opts = T.unsafe(nil), &blk); end

    # source://nokogiri/1.15.2/lib/nokogiri.rb#42
    def parse(string, url = T.unsafe(nil), encoding = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://nokogiri/1.15.2/lib/nokogiri/version/info.rb#200
    def uses_gumbo?; end

    # source://nokogiri/1.15.2/lib/nokogiri/version/info.rb#192
    def uses_libxml?(requirement = T.unsafe(nil)); end
  end
end

# source://nokogiri-html5-inference//lib/nokogiri/html5/inference/version.rb#4
module Nokogiri::HTML5
  class << self
    # source://nokogiri/1.15.2/lib/nokogiri/html5.rb#238
    def fragment(string, encoding = T.unsafe(nil), **options); end

    # source://nokogiri/1.15.2/lib/nokogiri/html5.rb#249
    def get(uri, options = T.unsafe(nil)); end

    # source://nokogiri/1.15.2/lib/nokogiri/html5.rb#232
    def parse(string, url = T.unsafe(nil), encoding = T.unsafe(nil), **options, &block); end

    # source://nokogiri/1.15.2/lib/nokogiri/html5.rb#260
    def read_and_encode(string, encoding); end

    private

    # source://nokogiri/1.15.2/lib/nokogiri/html5.rb#286
    def get_impl(uri, options = T.unsafe(nil)); end

    # source://nokogiri/1.15.2/lib/nokogiri/html5.rb#347
    def reencode(body, content_type = T.unsafe(nil)); end
  end
end

# :markup: markdown
#
#  The [HTML5 Spec](https://html.spec.whatwg.org/multipage/parsing.html) defines some very
#  precise context-dependent parsing rules which can make it challenging to "just parse" a
#  fragment of HTML without knowing the parent node -- also called the "context node" -- in
#  which it will be inserted.
#
#  Most content in an HTML5 document can be parsed assuming the parser's mode will be in the
#  ["in body" insertion
#  mode](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody), but there
#  are some notable exceptions. Perhaps the most problematic to web developers are the
#  table-related tags, which will not be parsed properly unless the parser is in the ["in
#  table" insertion
#  mode](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intable).
#
#  For example:
#
#  ``` ruby
#  Nokogiri::HTML5::DocumentFragment.parse("<td>foo</td>").to_html
#  # => "foo" # where did the tag go!?
#  ```
#
#  In the default "in body" mode, the parser will log an error, "Start tag 'td' isn't allowed
#  here", and drop the tag. This particular fragment must be parsed "in the context" of a
#  table in order to parse properly.
#
#  Thankfully, libgumbo and Nokogiri allow us to set the context node:
#
#  ``` ruby
#  Nokogiri::HTML5::DocumentFragment.new(
#    Nokogiri::HTML5::Document.new,
#    "<td>foo</td>",
#    "table"  # <--- this is the context node
#  ).to_html
#  # => "<tbody><tr><td>foo</td></tr></tbody>"
#  ```
#
#  This result is _almost_ correct, but we're seeing another HTML5 parsing rule in action:
#  there may be _intermediate parent tags_ that the HTML5 spec requires to be inserted by the
#  parser. In this case, the `<td>` tag must be wrapped in `<tbody><tr>` tags.
#
#  We can fix this to only return the tags we provided by using the `<template>` tag as the
#  context node, which the HTML5 spec provides exactly for this purpose:
#
#  ``` ruby
#  Nokogiri::HTML5::DocumentFragment.new(
#    Nokogiri::HTML5::Document.new,
#    "<td>foo</td>",
#    "template"  # <--- this is the context node
#  ).to_html
#  # => "<td>foo</td>"
#  ```
#
#  Huzzah! That works. And it's precisely what `Nokogiri::HTML5::Inference.parse` does:
#
#  ``` ruby
#  Nokogiri::HTML5::Inference.parse("<td>foo</td>").to_html
#  # => "<td>foo</td>"
#  ```
#
# source://nokogiri-html5-inference//lib/nokogiri/html5/inference/version.rb#5
module Nokogiri::HTML5::Inference
  class << self
    # call-seq: context(input) => (String | nil)
    #
    #  Based on the start of the input HTML5 string, make a guess about whether it's a full
    #  document or a document fragment; and if it's a fragment, whether we need to parse it
    #  within a specific context node.
    #
    #  [Parameters]
    #  - +input+ (String) The input HTML5 string, which may represent a document or a fragment.
    #
    #  [Returns]
    #    The String name of the context node required to parse the fragment, or +nil+ if the
    #    input represents a full document.
    #
    # source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#149
    def context(input); end

    # call-seq:
    #    parse(input, pluck: true) => (Nokogiri::HTML5::Document | Nokogiri::XML::NodeSet)
    #
    #  Based on the start of the input HTML5 string, guess whether it's a full document or a
    #  fragment and, using the fragment context node if necessary, parse it properly and
    #  return the correct set of nodes.
    #
    #  The keyword parameter +pluck+ can be set to +false+ to disable the narrowing of a
    #  parsed fragment to omit any intermediate parent nodes. This "plucking" is necessary,
    #  for example, when the input fragment begins with "<td>", which the HTML5 spec requires
    #  to be wrapped in <tt><tbody><tr>...</tr></tbody></tt> tags. By default, this method
    #  will return only the children of <tt><tbody><tr></tt>, but setting this flag to +false+
    #  will return the +tbody+ tag and its children.
    #
    #  [Parameters]
    #  - +input+ (String) The input HTML5 string, which may represent a document or a fragment.
    #
    #  [Keyword Parameters]
    #  - +pluck+ (Boolean) Default: +true+. Set to +false+ if you want the method to always
    #    return what Nokogiri parsed, without attempting to remove any sibling or intermediate
    #    parent nodes. This shouldn't be necessary if the library is working properly, but may
    #    be useful to allow user to work around a bad guess.
    #
    #  [Returns]
    #  - A +Nokogiri::HTML5::Document+ if the input appears to represent a full document.
    #  - A +Nokogiri::XML::NodeSet+ if the input appears to be a fragment.
    #
    # source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#121
    def parse(input, pluck: T.unsafe(nil)); end

    # call-seq: pluck_path(input) => (String | nil)
    #
    #  Based on the start of the input HTML5 fragment string, determine whether the fragment
    #  will need to be selected out of a parent node. This is necessary, for example, when the
    #  fragment begins with "<td>", a tag which the HTML5 spec requires to be wrapped in
    #  "<tbody><tr>...</tr></tbody>".
    #
    #  [Parameters]
    #  - +input+ (String) The input HTML5 string, which should represent a fragment (not a full document).
    #
    #  [Returns]
    #    The String XPath query of the context node required to parse the fragment, or +nil+
    #    if no plucking is necessary.
    #
    # source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#172
    def pluck_path(input); end
  end
end

# Regular expressions used to determine if we need to use a context node.
#
# source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#81
module Nokogiri::HTML5::Inference::ContextRegexp; end

# source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#82
Nokogiri::HTML5::Inference::ContextRegexp::DOCUMENT = T.let(T.unsafe(nil), Regexp)

# source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#83
Nokogiri::HTML5::Inference::ContextRegexp::HTML = T.let(T.unsafe(nil), Regexp)

# Tags that must be parsed in a specific HTML5 insertion mode, for which we must use a
# context node.
#
# source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#76
module Nokogiri::HTML5::Inference::ContextTags; end

# source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#77
Nokogiri::HTML5::Inference::ContextTags::HTML = T.let(T.unsafe(nil), Array)

# Regular expressions used to determine if we will need to skip an intermediate parent or
# otherwise narrow the fragment DOM that is returned.
#
# source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#88
module Nokogiri::HTML5::Inference::PluckRegexp; end

# source://nokogiri-html5-inference//lib/nokogiri/html5/inference.rb#89
Nokogiri::HTML5::Inference::PluckRegexp::BODY_OUTER = T.let(T.unsafe(nil), Regexp)

# source://nokogiri-html5-inference//lib/nokogiri/html5/inference/version.rb#6
Nokogiri::HTML5::Inference::VERSION = T.let(T.unsafe(nil), String)

module Nokogiri::Test
  class << self
    def __foreign_error_handler; end
  end
end
