# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `redis-session-store` gem.
# Please instead update this file by running `bin/tapioca gem redis-session-store`.


# Redis session storage for Rails, and for Rails only. Derived from
# the MemCacheStore code, simply dropping in Redis instead.
#
# source://redis-session-store//lib/redis-session-store.rb#5
class RedisSessionStore < ::ActionDispatch::Session::AbstractSecureStore
  # ==== Options
  # * +:key+ - Same as with the other cookie stores, key name
  # * +:redis+ - A hash with redis-specific options
  #   * +:url+ - Redis url, default is redis://localhost:6379/0
  #   * +:key_prefix+ - Prefix for keys used in Redis, e.g. +myapp:+
  #   * +:expire_after+ - A number in seconds for session timeout
  #   * +:client+ - Connect to Redis with given object rather than create one
  # * +:on_redis_down:+ - Called with err, env, and SID on Errno::ECONNREFUSED
  # * +:on_session_load_error:+ - Called with err and SID on Marshal.load fail
  # * +:serializer:+ - Serializer to use on session data, default is :marshal.
  #
  # ==== Examples
  #
  #     Rails.application.config.session_store :redis_session_store,
  #       key: 'your_session_key',
  #       redis: {
  #         expire_after: 120.minutes,
  #         key_prefix: 'myapp:session:',
  #         url: 'redis://localhost:6379/0'
  #       },
  #       on_redis_down: ->(*a) { logger.error("Redis down! #{a.inspect}") },
  #       serializer: :hybrid # migrate from Marshal to JSON
  #
  # @return [RedisSessionStore] a new instance of RedisSessionStore
  #
  # source://redis-session-store//lib/redis-session-store.rb#40
  def initialize(app, options = T.unsafe(nil)); end

  # Returns the value of attribute on_redis_down.
  #
  # source://redis-session-store//lib/redis-session-store.rb#53
  def on_redis_down; end

  # Sets the attribute on_redis_down
  #
  # @param value the value to set the attribute on_redis_down to.
  #
  # source://redis-session-store//lib/redis-session-store.rb#53
  def on_redis_down=(_arg0); end

  # Returns the value of attribute on_session_load_error.
  #
  # source://redis-session-store//lib/redis-session-store.rb#53
  def on_session_load_error; end

  # Sets the attribute on_session_load_error
  #
  # @param value the value to set the attribute on_session_load_error to.
  #
  # source://redis-session-store//lib/redis-session-store.rb#53
  def on_session_load_error=(_arg0); end

  private

  # source://redis-session-store//lib/redis-session-store.rb#121
  def decode(data); end

  # Returns the value of attribute default_options.
  #
  # source://redis-session-store//lib/redis-session-store.rb#57
  def default_options; end

  # source://redis-session-store//lib/redis-session-store.rb#149
  def delete_session(env, sid, options); end

  # source://redis-session-store//lib/redis-session-store.rb#154
  def destroy(env); end

  # source://redis-session-store//lib/redis-session-store.rb#149
  def destroy_session(env, sid, options); end

  # source://redis-session-store//lib/redis-session-store.rb#162
  def destroy_session_from_sid(sid, options = T.unsafe(nil)); end

  # source://redis-session-store//lib/redis-session-store.rb#169
  def determine_serializer(serializer); end

  # source://redis-session-store//lib/redis-session-store.rb#145
  def encode(session_data); end

  # source://redis-session-store//lib/redis-session-store.rb#102
  def find_session(env, sid); end

  # source://redis-session-store//lib/redis-session-store.rb#140
  def get_expiry(env, options); end

  # source://redis-session-store//lib/redis-session-store.rb#102
  def get_session(env, sid); end

  # Returns the value of attribute key.
  #
  # source://redis-session-store//lib/redis-session-store.rb#57
  def key; end

  # @return [Boolean]
  #
  # source://redis-session-store//lib/redis-session-store.rb#76
  def key_exists?(value); end

  # source://redis-session-store//lib/redis-session-store.rb#110
  def load_session_from_redis(sid); end

  # source://redis-session-store//lib/redis-session-store.rb#94
  def prefixed(sid); end

  # Returns the value of attribute redis.
  #
  # source://redis-session-store//lib/redis-session-store.rb#57
  def redis; end

  # Returns the value of attribute serializer.
  #
  # source://redis-session-store//lib/redis-session-store.rb#57
  def serializer; end

  # source://redis-session-store//lib/redis-session-store.rb#98
  def session_default_values; end

  # overrides method defined in rack to actually verify session existence
  # Prevents needless new sessions from being created in scenario where
  # user HAS session id, but it already expired, or is invalid for some
  # other reason, and session was accessed only for reading.
  #
  # @return [Boolean]
  #
  # source://redis-session-store//lib/redis-session-store.rb#63
  def session_exists?(env); end

  # source://redis-session-store//lib/redis-session-store.rb#126
  def set_session(env, sid, session_data, options = T.unsafe(nil)); end

  # source://redis-session-store//lib/redis-session-store.rb#86
  def verify_handlers!; end

  # source://redis-session-store//lib/redis-session-store.rb#126
  def write_session(env, sid, session_data, options = T.unsafe(nil)); end
end

# source://redis-session-store//lib/redis-session-store.rb#9
RedisSessionStore::ENV_SESSION_OPTIONS_KEY = T.let(T.unsafe(nil), String)

# Transparently migrates existing session values from Marshal to JSON
#
# source://redis-session-store//lib/redis-session-store.rb#191
class RedisSessionStore::HybridSerializer < ::RedisSessionStore::JsonSerializer
  class << self
    # source://redis-session-store//lib/redis-session-store.rb#194
    def load(value); end

    # @return [Boolean]
    #
    # source://redis-session-store//lib/redis-session-store.rb#202
    def needs_migration?(value); end
  end
end

# source://redis-session-store//lib/redis-session-store.rb#192
RedisSessionStore::HybridSerializer::MARSHAL_SIGNATURE = T.let(T.unsafe(nil), String)

# Uses built-in JSON library to encode/decode session
#
# source://redis-session-store//lib/redis-session-store.rb#180
class RedisSessionStore::JsonSerializer
  class << self
    # source://redis-session-store//lib/redis-session-store.rb#185
    def dump(value); end

    # source://redis-session-store//lib/redis-session-store.rb#181
    def load(value); end
  end
end

# source://redis-session-store//lib/redis-session-store.rb#16
RedisSessionStore::USE_INDIFFERENT_ACCESS = T.let(T.unsafe(nil), String)

# source://redis-session-store//lib/redis-session-store.rb#6
RedisSessionStore::VERSION = T.let(T.unsafe(nil), String)
