# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `stimulus_reflex` gem.
# Please instead update this file by running `bin/tapioca gem stimulus_reflex`.


# source://stimulus_reflex//lib/stimulus_reflex/version.rb#3
module StimulusReflex
  class << self
    # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#9
    def config; end

    # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#9
    def configuration; end

    # @yield [configuration]
    #
    # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#5
    def configure; end
  end
end

# source://stimulus_reflex//lib/stimulus_reflex/utils/attribute_builder.rb#3
module StimulusReflex::AttributeBuilder
  # source://stimulus_reflex//lib/stimulus_reflex/utils/attribute_builder.rb#4
  def build_data_attrs(dataset, dataset_all); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/attribute_builder.rb#14
  def build_underscored(attrs); end
end

# source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#4
class StimulusReflex::Broadcaster
  # @return [Broadcaster] a new instance of Broadcaster
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#8
  def initialize(reflex); end

  # abstract methods to be implemented by subclasses
  #
  # @raise [NotImplementedError]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#56
  def broadcast(*args); end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#45
  def broadcast_error(data: T.unsafe(nil), error: T.unsafe(nil)); end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#36
  def broadcast_forbid(data: T.unsafe(nil)); end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#27
  def broadcast_halt(data: T.unsafe(nil)); end

  # Returns the value of attribute cable_ready.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#5
  def cable_ready; end

  # Returns the value of attribute logger.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#5
  def logger; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#15
  def nothing?; end

  # Returns the value of attribute operations.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#5
  def operations; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#19
  def page?; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#6
  def payload(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#6
  def permanent_attribute_name(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute reflex.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#5
  def reflex; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#23
  def selector?; end

  # @raise [NotImplementedError]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#64
  def to_s; end

  # @raise [NotImplementedError]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/broadcaster.rb#60
  def to_sym; end
end

# source://stimulus_reflex//lib/stimulus_reflex/broadcasters/update.rb#4
module StimulusReflex::Broadcasters; end

# source://stimulus_reflex//lib/stimulus_reflex/broadcasters/update.rb#5
class StimulusReflex::Broadcasters::Update
  include ::CableReady::Identifiable

  # @return [Update] a new instance of Update
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/update.rb#8
  def initialize(key, value, reflex); end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/update.rb#18
  def html; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/update.rb#14
  def selector; end
end

# source://stimulus_reflex//lib/stimulus_reflex/cable_readiness.rb#4
module StimulusReflex::CableReadiness
  # source://stimulus_reflex//lib/stimulus_reflex/cable_readiness.rb#7
  def initialize(*args, **kwargs); end

  # Returns the value of attribute cable_ready.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/cable_readiness.rb#5
  def cable_ready; end
end

# source://stimulus_reflex//lib/stimulus_reflex/cable_ready_channels.rb#4
class StimulusReflex::CableReadyChannels
  # @return [CableReadyChannels] a new instance of CableReadyChannels
  #
  # source://stimulus_reflex//lib/stimulus_reflex/cable_ready_channels.rb#7
  def initialize(reflex); end

  # source://stimulus_reflex//lib/stimulus_reflex/cable_ready_channels.rb#5
  def [](*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/cable_ready_channels.rb#13
  def cable_ready_channels; end

  # source://stimulus_reflex//lib/stimulus_reflex/cable_ready_channels.rb#21
  def method_missing(name, *args); end

  # source://stimulus_reflex//lib/stimulus_reflex/cable_ready_channels.rb#17
  def stimulus_reflex_channel; end

  private

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/cable_ready_channels.rb#33
  def respond_to_missing?(name, include_all); end
end

# source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#6
module StimulusReflex::Callbacks
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::ActiveSupport::Callbacks

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::StimulusReflex::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::ActiveSupport::DescendantsTracker

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
    def __callbacks?; end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
    def __callbacks?; end
  end
end

# source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#0
module StimulusReflex::Callbacks::ClassMethods
  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#33
  def after_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#33
  def append_after_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#37
  def append_around_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#29
  def append_before_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#37
  def around_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#29
  def before_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#45
  def prepend_after_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#49
  def prepend_around_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#41
  def prepend_before_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#57
  def skip_after_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#61
  def skip_around_reflex(*args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#53
  def skip_before_reflex(*args, &block); end

  private

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#71
  def add_callback(kind, *args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#89
  def insert_callbacks(callbacks, block = T.unsafe(nil)); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#105
  def normalize_callback_option!(options, from, to); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#100
  def normalize_callback_options!(options); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#83
  def omit_callback(kind, *args, &block); end

  # source://stimulus_reflex//lib/stimulus_reflex/callbacks.rb#77
  def prepend_callback(kind, *args, &block); end
end

# source://stimulus_reflex//lib/stimulus_reflex/concern_enhancer.rb#4
module StimulusReflex::ConcernEnhancer
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::StimulusReflex::ConcernEnhancer::ClassMethods
end

# source://stimulus_reflex//lib/stimulus_reflex/concern_enhancer.rb#0
module StimulusReflex::ConcernEnhancer::ClassMethods
  # source://stimulus_reflex//lib/stimulus_reflex/concern_enhancer.rb#8
  def method_missing(name, *args); end

  private

  # source://stimulus_reflex//lib/stimulus_reflex/concern_enhancer.rb#27
  def respond_to_missing?(name, include_all = T.unsafe(nil)); end
end

# source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#16
class StimulusReflex::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#29
  def initialize; end

  # Returns the value of attribute logger.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def logger; end

  # Sets the attribute logger
  #
  # @param value the value to set the attribute logger to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def logger=(_arg0); end

  # Returns the value of attribute logging.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def logging; end

  # Sets the attribute logging
  #
  # @param value the value to set the attribute logging to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def logging=(_arg0); end

  # Returns the value of attribute middleware.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def middleware; end

  # Sets the attribute middleware
  #
  # @param value the value to set the attribute middleware to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def middleware=(_arg0); end

  # Returns the value of attribute morph_operation.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def morph_operation; end

  # Sets the attribute morph_operation
  #
  # @param value the value to set the attribute morph_operation to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def morph_operation=(_arg0); end

  # Returns the value of attribute on_failed_sanity_checks.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def on_failed_sanity_checks; end

  # Sets the attribute on_failed_sanity_checks
  #
  # @param value the value to set the attribute on_failed_sanity_checks to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def on_failed_sanity_checks=(_arg0); end

  # Returns the value of attribute on_missing_default_urls.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def on_missing_default_urls; end

  # Sets the attribute on_missing_default_urls
  #
  # @param value the value to set the attribute on_missing_default_urls to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def on_missing_default_urls=(_arg0); end

  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#21
  def on_new_version_available; end

  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#25
  def on_new_version_available=(_); end

  # Returns the value of attribute parent_channel.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def parent_channel; end

  # Sets the attribute parent_channel
  #
  # @param value the value to set the attribute parent_channel to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def parent_channel=(_arg0); end

  # Returns the value of attribute precompile_assets.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def precompile_assets; end

  # Sets the attribute precompile_assets
  #
  # @param value the value to set the attribute precompile_assets to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def precompile_assets=(_arg0); end

  # Returns the value of attribute replace_operation.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def replace_operation; end

  # Sets the attribute replace_operation
  #
  # @param value the value to set the attribute replace_operation to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#17
  def replace_operation=(_arg0); end
end

# source://stimulus_reflex//lib/stimulus_reflex/configuration.rb#19
StimulusReflex::Configuration::DEFAULT_LOGGING = T.let(T.unsafe(nil), Proc)

# source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#5
class StimulusReflex::Dataset < ::OpenStruct
  include ::StimulusReflex::AttributeBuilder

  # @return [Dataset] a new instance of Dataset
  #
  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#10
  def initialize(data = T.unsafe(nil)); end

  # Returns the value of attribute attrs.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#8
  def attrs; end

  # Sets the attribute attrs
  #
  # @param value the value to set the attribute attrs to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#8
  def attrs=(_arg0); end

  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#27
  def boolean; end

  # Returns the value of attribute data_attrs.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#8
  def data_attrs; end

  # Sets the attribute data_attrs
  #
  # @param value the value to set the attribute data_attrs to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#8
  def data_attrs=(_arg0); end

  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#31
  def numeric; end

  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#19
  def signed; end

  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#23
  def unsigned; end

  private

  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#37
  def cast_boolean(value); end

  # source://stimulus_reflex//lib/stimulus_reflex/dataset.rb#41
  def false_values; end
end

# source://stimulus_reflex//lib/stimulus_reflex/element.rb#6
class StimulusReflex::Element < ::OpenStruct
  include ::StimulusReflex::AttributeBuilder

  # @return [Element] a new instance of Element
  #
  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#15
  def initialize(data = T.unsafe(nil)); end

  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#23
  def attributes; end

  # Returns the value of attribute attrs.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#9
  def attrs; end

  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#13
  def boolean(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute dataset.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#9
  def data_attributes; end

  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#13
  def data_attrs(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute dataset.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#9
  def dataset; end

  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#13
  def numeric(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#13
  def signed(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#27
  def to_dom_id; end

  # source://stimulus_reflex//lib/stimulus_reflex/element.rb#13
  def unsigned(*_arg0, **_arg1, &_arg2); end
end

# source://stimulus_reflex//lib/stimulus_reflex/engine.rb#6
class StimulusReflex::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end

# If you don't want to precompile StimulusReflex's assets (eg. because you're using webpack),
# you can do this in an initializer:
#
# config.after_initialize do
#   config.assets.precompile -= StimulusReflex::Engine::PRECOMPILE_ASSETS
# end
#
# source://stimulus_reflex//lib/stimulus_reflex/engine.rb#18
StimulusReflex::Engine::PRECOMPILE_ASSETS = T.let(T.unsafe(nil), Array)

# source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#4
module StimulusReflex::HTML; end

# source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#5
class StimulusReflex::HTML::Document
  # @return [Document] a new instance of Document
  #
  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#23
  def initialize(html); end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#10
  def document_element; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#8
  def element(*_arg0, **_arg1, &_arg2); end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#30
  def empty?; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#19
  def inner_html; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#38
  def match(selector); end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#14
  def outer_html; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#34
  def parsing_class; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#14
  def to_html; end
end

# source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#6
StimulusReflex::HTML::Document::DEFAULT_HTML_WITHOUT_FORMAT = T.let(T.unsafe(nil), Integer)

# source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#42
class StimulusReflex::HTML::Document::Match < ::Struct
  # Returns the value of attribute element
  #
  # @return [Object] the current value of element
  def element; end

  # Sets the attribute element
  #
  # @param value [Object] the value to set the attribute element to.
  # @return [Object] the newly set value
  def element=(_); end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#53
  def inner_html; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#45
  def outer_html; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#43
  def present?(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document.rb#49
  def to_html; end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://stimulus_reflex//lib/stimulus_reflex/html/document_fragment.rb#5
class StimulusReflex::HTML::DocumentFragment < ::StimulusReflex::HTML::Document
  # source://stimulus_reflex//lib/stimulus_reflex/html/document_fragment.rb#10
  def document_element; end

  # source://stimulus_reflex//lib/stimulus_reflex/html/document_fragment.rb#6
  def parsing_class; end
end

# source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#4
class StimulusReflex::Logger
  # @return [Logger] a new instance of Logger
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#10
  def initialize(reflex); end

  # Returns the value of attribute current_operation.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#6
  def current_operation; end

  # Sets the attribute current_operation
  #
  # @param value the value to set the attribute current_operation to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#6
  def current_operation=(_arg0); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#8
  def debug(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#8
  def error(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#8
  def fatal(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#8
  def info(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#16
  def log_all_operations; end

  # Returns the value of attribute logger.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#5
  def logger; end

  # Returns the value of attribute reflex.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#6
  def reflex; end

  # Sets the attribute reflex
  #
  # @param value the value to set the attribute reflex to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#6
  def reflex=(_arg0); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#8
  def unknown(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#8
  def warn(*_arg0, **_arg1, &_arg2); end

  private

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#27
  def config_logging; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#88
  def connection_id; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#83
  def connection_id_full; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#53
  def id; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#49
  def id_full; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#96
  def method_missing(name, *args); end

  # END TODO remove
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#67
  def mode; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#75
  def operation; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#79
  def operation_counter; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#116
  def private_instance_methods; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#62
  def reflex_id; end

  # TODO: remove for v4
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#58
  def reflex_id_full; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#45
  def reflex_info; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#106
  def respond_to_missing?(name, include_all); end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#71
  def selector; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#41
  def session_id; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#36
  def session_id_full; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/logger.rb#92
  def timestamp; end
end

# source://stimulus_reflex//lib/stimulus_reflex/broadcasters/nothing_broadcaster.rb#4
class StimulusReflex::NothingBroadcaster < ::StimulusReflex::Broadcaster
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/nothing_broadcaster.rb#5
  def broadcast(_, data); end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/nothing_broadcaster.rb#15
  def nothing?; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/nothing_broadcaster.rb#23
  def to_s; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/nothing_broadcaster.rb#19
  def to_sym; end
end

# source://stimulus_reflex//lib/stimulus_reflex/broadcasters/page_broadcaster.rb#4
class StimulusReflex::PageBroadcaster < ::StimulusReflex::Broadcaster
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/page_broadcaster.rb#5
  def broadcast(selectors, data); end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/page_broadcaster.rb#31
  def page?; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/page_broadcaster.rb#35
  def to_s; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/page_broadcaster.rb#27
  def to_sym; end
end

# source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#6
class StimulusReflex::Reflex
  include ::StimulusReflex::CableReadiness
  include ::StimulusReflex::VersionChecker
  include ::StimulusReflex::Callbacks
  include ::ActiveSupport::Callbacks
  include ::ActiveSupport::Rescuable
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::CableReady::Identifiable
  extend ::StimulusReflex::Callbacks::ClassMethods
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveSupport::Rescuable::ClassMethods

  # @return [Reflex] a new instance of Reflex
  #
  # source://stimulus_reflex//lib/stimulus_reflex/cable_readiness.rb#7
  def initialize(*args, **kwargs); end

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
  def __callbacks; end

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
  def __callbacks?; end

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#963
  def _process_callbacks; end

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#951
  def _run_process_callbacks(&block); end

  # END TODO: remove
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def action_name(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#19
  def broadcast(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#19
  def broadcast_error(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#19
  def broadcast_forbid(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#19
  def broadcast_halt(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute broadcaster.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#15
  def broadcaster; end

  # Returns the value of attribute channel.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#15
  def channel; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#17
  def connection(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#100
  def controller; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#112
  def controller?; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#18
  def controller_class(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute reflex_data.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#15
  def data; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#140
  def default_reflex; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def element(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#18
  def flash(*_arg0, **_arg1, &_arg2); end

  # Indicates if the callback chain was halted via a throw(:forbidden) in a before_reflex callback.
  #
  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#136
  def forbidden?; end

  # Indicates if the callback chain was halted via a throw(:abort) in a before_reflex callback.
  # SEE: https://api.rubyonrails.org/classes/ActiveSupport/Callbacks.html
  # IMPORTANT: The reflex will not re-render the page if the callback chain is halted
  #
  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#131
  def halted?; end

  # Returns the value of attribute headers.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#14
  def headers; end

  # Sets the attribute headers
  #
  # @param value the value to set the attribute headers to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#14
  def headers=(_arg0); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def id(*_arg0, **_arg1, &_arg2); end

  # END TODO: remove
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#45
  def logger; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def method_name(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#86
  def morph(selectors, html = T.unsafe(nil)); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def npm_version(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#144
  def params; end

  # Returns the value of attribute payload.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#14
  def payload; end

  # Sets the attribute payload
  #
  # @param value the value to set the attribute payload to.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#14
  def payload=(_arg0); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def permanent_attribute_name(*_arg0, **_arg1, &_arg2); end

  # Invoke the reflex action specified by `name` and run all callbacks
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#124
  def process(name, *args); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def reflex_controller(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute reflex_data.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#15
  def reflex_data; end

  # TODO: remove this for v4
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#39
  def reflex_id; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#116
  def render(*args); end

  # morphdom needs content to be wrapped in an element with the same id when children_only: true
  # Oddly, it doesn't matter if the target element is a div! See: https://docs.stimulusreflex.com/appendices/troubleshooting#different-element-type-altogether-who-cares-so-long-as-the-css-selector-matches
  # Used internally to allow automatic partial collection rendering, but also useful to library users
  # eg. `morph dom_id(@posts), render_collection(@posts)`
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#152
  def render_collection(resource, content = T.unsafe(nil)); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#49
  def request; end

  # source://activesupport/7.1.3.4/lib/active_support/rescuable.rb#15
  def rescue_handlers; end

  # source://activesupport/7.1.3.4/lib/active_support/rescuable.rb#15
  def rescue_handlers=(_arg0); end

  # source://activesupport/7.1.3.4/lib/active_support/rescuable.rb#15
  def rescue_handlers?; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def selectors(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#18
  def session(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#17
  def stream_name(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def suppress_logging(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def tab_id(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def url(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def version(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def xpath_controller(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex.rb#22
  def xpath_element(*_arg0, **_arg1, &_arg2); end

  class << self
    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks; end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks=(value); end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks?; end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#955
    def _process_callbacks; end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#959
    def _process_callbacks=(value); end

    # source://activesupport/7.1.3.4/lib/active_support/rescuable.rb#15
    def rescue_handlers; end

    # source://activesupport/7.1.3.4/lib/active_support/rescuable.rb#15
    def rescue_handlers=(value); end

    # source://activesupport/7.1.3.4/lib/active_support/rescuable.rb#15
    def rescue_handlers?; end
  end
end

# source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#3
class StimulusReflex::ReflexData
  # @return [ReflexData] a new instance of ReflexData
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#6
  def initialize(data); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#30
  def arguments; end

  # Returns the value of attribute data.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#4
  def data; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#38
  def element; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#50
  def form_data; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#58
  def form_params; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#66
  def id; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#26
  def method_name; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#88
  def npm_version; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#54
  def params; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#42
  def permanent_attribute_name; end

  # END TODO remove
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#84
  def reflex_controller; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#10
  def reflex_name; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#16
  def selectors; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#46
  def suppress_logging; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#70
  def tab_id; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#22
  def target; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#34
  def url; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#62
  def url_params; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#92
  def version; end

  # TODO: remove this in v4
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#75
  def xpath_controller; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#79
  def xpath_element; end

  private

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_data.rb#98
  def object_with_indifferent_access(object); end
end

# source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#3
class StimulusReflex::ReflexFactory
  # @return [ReflexFactory] a new instance of ReflexFactory
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#8
  def initialize(channel, data); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#13
  def call; end

  # Returns the value of attribute channel.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#4
  def channel; end

  # Returns the value of attribute data.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#4
  def data; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#6
  def method_name(*_arg0, **_arg1, &_arg2); end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#6
  def reflex_name(*_arg0, **_arg1, &_arg2); end

  private

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#48
  def default_reflex?; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#34
  def reflex_class; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#42
  def reflex_method; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#52
  def safe_ancestors; end

  # source://stimulus_reflex//lib/stimulus_reflex/reflex_factory.rb#20
  def verify_method_name!; end
end

# source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#4
class StimulusReflex::ReflexMethodInvocationPolicy
  # @return [ReflexMethodInvocationPolicy] a new instance of ReflexMethodInvocationPolicy
  #
  # source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#7
  def initialize(method, arguments); end

  # Returns the value of attribute arguments.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#5
  def arguments; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#17
  def arguments?; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#13
  def no_arguments?; end

  # Returns the value of attribute optional_params.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#5
  def optional_params; end

  # Returns the value of attribute required_params.
  #
  # source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#5
  def required_params; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/policies/reflex_invocation_policy.rb#21
  def unknown?; end
end

# source://stimulus_reflex//lib/stimulus_reflex/request_parameters.rb#4
class StimulusReflex::RequestParameters
  # @return [RequestParameters] a new instance of RequestParameters
  #
  # source://stimulus_reflex//lib/stimulus_reflex/request_parameters.rb#5
  def initialize(params:, req:, url:); end

  # source://stimulus_reflex//lib/stimulus_reflex/request_parameters.rb#11
  def apply!; end
end

# source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#3
class StimulusReflex::SanityChecker
  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#70
  def caching_not_enabled?; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#34
  def check_caching_enabled; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#54
  def check_default_url_config; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#82
  def default_url_config_set?; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#78
  def initializer_missing?; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#74
  def using_null_store?; end

  # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#90
  def warn_and_exit(text); end

  class << self
    # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#5
    def check!; end

    private

    # @return [Boolean]
    #
    # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#25
    def called_by_generate_config?; end

    # @return [Boolean]
    #
    # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#19
    def called_by_installer?; end

    # @return [Boolean]
    #
    # source://stimulus_reflex//lib/stimulus_reflex/utils/sanity_checker.rb#29
    def called_by_rake?; end
  end
end

# source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#4
class StimulusReflex::SelectorBroadcaster < ::StimulusReflex::Broadcaster
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#42
  def append_morph(selectors, html); end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#5
  def broadcast(_, data = T.unsafe(nil)); end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#38
  def morphs; end

  # @return [Boolean]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#50
  def selector?; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#54
  def to_s; end

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#46
  def to_sym; end

  private

  # source://stimulus_reflex//lib/stimulus_reflex/broadcasters/selector_broadcaster.rb#60
  def create_update_collection(selectors, html); end
end

# source://stimulus_reflex//lib/stimulus_reflex/utils/colorize.rb#4
module StimulusReflex::Utils; end

# source://stimulus_reflex//lib/stimulus_reflex/utils/colorize.rb#5
module StimulusReflex::Utils::Colorize; end

# source://stimulus_reflex//lib/stimulus_reflex/utils/colorize.rb#6
StimulusReflex::Utils::Colorize::COLORS = T.let(T.unsafe(nil), Hash)

# source://stimulus_reflex//lib/stimulus_reflex/version.rb#4
StimulusReflex::VERSION = T.let(T.unsafe(nil), String)

# source://stimulus_reflex//lib/stimulus_reflex/version_checker.rb#7
module StimulusReflex::VersionChecker
  # @raise [VersionMismatchError]
  #
  # source://stimulus_reflex//lib/stimulus_reflex/version_checker.rb#8
  def check_version!; end
end

# source://stimulus_reflex//lib/stimulus_reflex/version_checker.rb#4
class StimulusReflex::VersionMismatchError < ::StandardError; end
