# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `thread-local` gem.
# Please instead update this file by running `bin/tapioca gem thread-local`.


# source://thread-local//lib/thread/local/version.rb#24
module Thread::Local
  # Get the current thread-local instance. Create it if required.
  #
  # source://thread-local//lib/thread/local.rb#36
  def instance; end

  # Assigns the current thread-local instance.
  #
  # source://thread-local//lib/thread/local.rb#51
  def instance=(instance); end

  # Instantiate a new thread-local object.
  # By default, invokes {new} to generate the instance.
  #
  # source://thread-local//lib/thread/local.rb#30
  def local; end
end

# source://thread-local//lib/thread/local/version.rb#25
Thread::Local::VERSION = T.let(T.unsafe(nil), String)
