---
services:
  whisper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=large-v3
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=en #optional
    volumes:
      - './recordings:/app/recordings'
      - './models:/app/models'
      - './transcriptions:/app/transcriptions'
      # - /path/to/faster-whisper/data:/config
    ports:
      - 10300:10300
    restart: unless-stopped
