# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Codeable`.
# Please instead update this file by running `bin/tapioca dsl Codeable`.


module Codeable
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def codes; end
    def codes=(value); end
    def codes?; end
  end

  module GeneratedInstanceMethods
    def codes; end
    def codes=(value); end
    def codes?; end
  end
end
